### ISSUE TITLE
possible patterns / main discussion

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/mukla#1]
```js
// possible:
// mukla().equal(title, actual, expected)
// mukla().then(title, fn)
// mukla().should(title, fn)
// mukla().should(title).then(title, fn)
// mukla().should(title).then(title, fn).then(title, fn)
// mukla().should(title).equal(title, actual, expected)

// not possible:
//
// cuz', `.then` requires to have `fn`, so chain assertion methods after `.then` are not reasonable
// if you want assertions open new `.should` or just put them on `.then`s `fn` function
//
// mukla().then(title).equal(title, actual, expected)
//
// cuz', if you want to create `next test/group/nesting` just use `.should`
// mukla().should(title, fn).then(title, fn)

// scenario #1, should count 1 test?
// should show assertion titles? maybe configurable with opts?
// then `.then` will be as `.describe` in mocha
// for grouping/nesting.
mukla('package-name:', opts)
.then('should pass when', function(context) {
  mukla.equal('given string is `one two`', context.str, 'one two');
  mukla.equal('given is typeof string', typeof context.str, 'string');
})
.run(context); // object, array or string? in this is case object

// scenario #2, should count 1 or 3 test(s)?
// should show assertion titles? maybe configurable with opts?
// then `.should` will be as `.describe` in mocha
// for grouping/nesting.
mukla('package-yeah:', opts)
.should('pass when', function(contextString) {
  mukla.equal('given string is `one two`', contextString, 'one two');
  mukla.equal('given is typeof string', typeof contextString, 'string');
  mukla.equal('given be with length 7', contextString.length, 7);
})
.run('one two');

// scenario #3, how much should be the tests count, i think two?
mukla('package-beta:', opts)
.should('pass when', 2)
.then('string given', function(ctx) {
  mukla.equal('string is `one two`', ctx.str, 'one two');
  mukla.equal('is typeof string', typeof ctx.str, 'string');
  mukla.equal('be with length 7', ctx.str.length, 7);
})
.then('array given', function(ctx) {
  mukla.deepEqual('array is `one two`', ctx.arr, [1,2,3]);
  mukla.equal('is typeof array', ctx.arr instanceof Array, true);
  mukla.equal('be with length 3', ctx.arr.length, 3);
})
.should('fail when', 1)
.then('object given', function(ctx) {
  mukla.throws('Error: "cant give an object"', fixture, Error);
  mukla.equal('error is instanceof Error', fixture instanceof Error, true);
  mukla.falsey(' ctx.obj be falsey value', ctx.obj);
})
.run({
  str: 'one two',
  arr: [1,2,3],
  obj: {one: 123}
});

// scenario #4, should count 3 tests!
// `.should` is just for nesting, like `.describe` in mocha
// for grouping
mukla('package-gama:', opts)
.should('pass when')
.equal('given string be `one two`', str, 'one two')
.equal('given be typeof string', typeof str, 'string')
.equal('given be with length 7', str.length, 7)
.run()

// scenario #5, should count 3 tests?
mukla('package-two:', opts)
.equal('should given string be `one two`', str, 'one two')
.equal('should given be typeof string', typeof str, 'string')
.equal('should given be with length 7', str.length, 7)
.run()
```

**Comment by tunnckoCore** [comment]
But this flexibily costs. How to count how many tests have? Also.. nested outputs..

Possible scenarios with this flexibility...
- mukla().equal(title, val1, val2) (assertion methods, at all)
- mukla().should(title).then(title, fn)
- mukla().should(title).equal(title, val1, val2)
- mukla().should(title, fn)

What about when (3 or 6 tests should be?)
```js
mukla('anonymize-ip3:', {})
.should('these things', 3).be('be equal', function() {
  mukla.equal('two arrays', [1,2,3], [1,2,3])
  mukla.equal('two objects', {one: 123}, {one: 123})
  mukla.equal('two strings', '[1,2,3]', '[1,2,3]')
})
.should('one plus one', 1).equal('be equal to two', 1+1,2)
.should('two plus two', 2).equal('be equal to four', 2+2,4)
.run();
```

**Comment by tunnckoCore** [comment]
Or just count `.then/.be` and `.assertion` methods as "tests" that would be in count? So above example would count 3 tests. If some assert in `.be('be equal', function() {` fail, it would count 2 passing tests 1 failing?

**Comment by tunnckoCore** [comment]
### API

#### 1) .equal([title], \<actual\>, \<expected\>) (with equal, means all assert methods)
#### 2) .should(\<title\>, [function], [number]) with aliases: .when/.describe
#### 3) .then(\<title\>, \<function\>, [number]) with aliases: .be/.it/.test

***

##### 1) about assertion methods
- `title` should be required when only mukla().equal() is used. Because they are the tests actually.
- `title` should be required when mukla().should(title).equal() is used? maybe if only option for showing subtitles (nested titles) is enabled?

##### 2) about `.should` method
- if only `title` then must have `.then` or `.equal` after it..
- when `title` and `function` it cant have `.equal` after it? maybe only `.then` and another `.should`?

##### 3) about `.then` method
- it cant be after `.should(title, fn)`
- it cant have `.equal` after it

Every `function` will be bind to promise.then, so all is full async and pretty easy.  
For that is this `number`, which is for defining order of execution. From where come another question.. if not defined how to be based the id, which will be answered after `counting tests` problem.

**Comment by tunnckoCore** [comment]
@jonschlinkert @sindresorhus @johnotander, thoughts, please? lol
Too many questions. I just want to play. But who knows, one day it can be something great? :)

**Comment by tunnckoCore** [comment]
One thing is clear for me from a while.. flexibility costs.

**Comment by tunnckoCore** [comment]
@yoshuawuyts @jonathanong @hallas @travisjeffery

**Comment by jonathanong** [comment]
not ditching mocha, sorry :P

**Comment by tunnckoCore** [comment]
> not ditching mocha, sorry :P

There must have only one testing framework in the wild? Please, this state is ridiculous.

The idea here isn't to replace mocha or copy it. Here I just want thoughts, not implementations. Just discussion what is good, what is bad, cuz I'm "1 year old baby", specially in node.js community.

**Comment by yoshuawuyts** [comment]
[tape](https://github.com/substack/tape) has me covered already.

**Comment by tunnckoCore** [comment]
> tape has me covered already.

Me too, also mocha. But we can't stick with them forever :) Well, take it so.. I just want to play.
And want to realize this and I'm curious which should I count as "test" - like ending of other frameworks "tests 15, pass 15, fail 0", especially for scenario 3.

> Don't see how promises would be an improvement.

Smaller codebase and lower deps.

**Comment by tunnckoCore** [comment]
ref #4 pure awesomeness of BDD style

**Comment by tunnckoCore** [comment]
close, https://github.com/tunnckoCore/mukla/issues/4#issuecomment-96284588
